import 'package:firebase_database/firebase_database.dart';

class Todo {
  //Each to-do item is unique and has its own key.
  //Each item has a name or subject, a flag to keep track of its completion or completed and userId of who created this item.
  //To create a new todo, all prameters except key is required to pass into the constructor Todo().
  //The key is automatically generated by RTDB and stored when new todo is added.
  String key;
  String subject;
  bool completed;
  String userId;

  Todo(this.subject, this.userId, this.completed);

  //When data is fetched from Firebase RTDB, it is in json format. Hence we have the Todo.fromSnapshot(DataSnapshot snapshot) allows us to map data from json format to Todo format.
  Todo.fromSnapshot(DataSnapshot snapshot) :
        key = snapshot.key,
        userId = snapshot.value["userId"],
        subject = snapshot.value["subject"],
        completed = snapshot.value["completed"];

  //The toJson() does the opposite which is to map the data back into json format before we upload into Firebase RTDB
  toJson() {
    return {
      "userId": userId,
      "subject": subject,
      "completed": completed,
    };
  }
}